export interface IMedicineFormData {
  allow_return: boolean;
  allow_warranty_claim: boolean;
  barcode: string;
  brand_id: string;
  bundle_offer: string;
  calling_name: string;
  category_id: string;
  current_stock: number;
  default_unit_id: string;
  description: string;
  distributor_id: string;
  generic_name: string;
  is_active: boolean;
  manufacturer_id: string;
  maximum_stock: number;
  meta_description: string;
  meta_keyword: string;
  meta_title: string;
  minimum_stock: number;
  mrp: number;
  name: string;
  offered_price: number;
  overview: string;
  preview_media_id: null | string;
  product_number: string;
  product_video_url: string;
  purchase_price: number;
  rack_no: string;
  reorder_level: number;
  return_period_days: number;
  selling_price: number;
  shipping_cost: number;
  sku: string;
  status: string;
  supplier_id: string;
  tag_name: string;
  tax_rate: number;
  track_expiry_alert: boolean;
  unit_id: string;
  weight: number;
}

export const defaultMedicineData: IMedicineFormData = {
  allow_return: false,
  allow_warranty_claim: true,
  barcode: "",
  brand_id: "",
  bundle_offer: "",
  calling_name: "",
  category_id: "",
  current_stock: 1,
  default_unit_id: "",
  description: "",
  distributor_id: "",
  generic_name: "",
  is_active: true,
  manufacturer_id: "",
  maximum_stock: 1,
  meta_description: "",
  meta_keyword: "",
  meta_title: "",
  minimum_stock: 1,
  mrp: 1,
  name: "",
  offered_price: 1,
  overview: "",
  preview_media_id: null,
  product_number: "",
  product_video_url: "",
  purchase_price: 1,
  rack_no: "",
  reorder_level: 1,
  return_period_days: 1,
  selling_price: 1,
  shipping_cost: 1,
  sku: "",
  status: "",
  supplier_id: "",
  tag_name: "",
  tax_rate: 1,
  track_expiry_alert: true,
  unit_id: "",
  weight: 1,
};
